resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/18/0.yaml

allow-newer: true

packages:
  - proto3-suite

extra-deps:
  - github: awakesecurity/proto3-wire
    commit: 9b1c178f8a23a5f03237cb77cce403bc386da523

nix:
  packages:
    - zlib.dev
    - zlib.out
