resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/18/0.yaml

allow-newer: true

packages:
  - .

extra-deps:
  - github: awakesecurity/proto3-wire
    commit: 8096a1e19431af603655e5c1f2488b5db907836c

nix:
  packages:
    - zlib.dev
    - zlib.out
