resolver: nightly-2025-01-16

allow-newer: true

packages:
  - .

extra-deps:
  - github: awakesecurity/proto3-wire
    commit: 6fdf0eb93b2028ade0e3e011ce8429c94546839e

nix:
  packages:
    - zlib.dev
    - zlib.out
