{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
-- | Generated by Haskell protocol buffer compiler. DO NOT EDIT!
module Proto3.Suite.DotProto.Generate.JSONPBProto where
import qualified Prelude as Hs
import qualified Proto3.Suite.DotProto as HsProtobuf
import qualified Proto3.Suite.Types as HsProtobuf
import qualified Proto3.Suite.Class as HsProtobuf
import qualified Proto3.Wire as HsProtobuf
import Control.Applicative ((<*>), (<|>))
import qualified Data.Text.Lazy as Hs (Text)
import qualified Data.ByteString as Hs
import qualified Data.String as Hs (fromString)
import qualified Data.Vector as Hs (Vector)
import qualified Data.Int as Hs (Int16, Int32, Int64)
import qualified Data.Word as Hs (Word16, Word32, Word64)
import qualified GHC.Generics as Hs
import qualified GHC.Enum as Hs
 
data SignedInts = SignedInts{signedIntsS32 :: Hs.Int32,
                             signedIntsS64 :: Hs.Int64}
                deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
 
instance HsProtobuf.Named SignedInts where
        nameOf _ = (Hs.fromString "SignedInts")
 
instance HsProtobuf.Message SignedInts where
        encodeMessage _
          SignedInts{signedIntsS32 = signedIntsS32,
                     signedIntsS64 = signedIntsS64}
          = (Hs.mconcat
               [(HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 0)
                   (HsProtobuf.Signed signedIntsS32)),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 1)
                   (HsProtobuf.Signed signedIntsS64))])
        decodeMessage _
          = (Hs.pure SignedInts) <*>
              ((Hs.pure HsProtobuf.signed) <*>
                 (HsProtobuf.at HsProtobuf.decodeMessageField
                    (HsProtobuf.FieldNumber 0)))
              <*>
              ((Hs.pure HsProtobuf.signed) <*>
                 (HsProtobuf.at HsProtobuf.decodeMessageField
                    (HsProtobuf.FieldNumber 1)))
        dotProto _
          = [(HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 0)
                (HsProtobuf.Prim HsProtobuf.SInt32)
                (HsProtobuf.Single "s32")
                []
                Hs.Nothing),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 1)
                (HsProtobuf.Prim HsProtobuf.SInt64)
                (HsProtobuf.Single "s64")
                []
                Hs.Nothing)]
 
data Scalar32 = Scalar32{scalar32I32 :: Hs.Int32,
                         scalar32U32 :: Hs.Word32, scalar32S32 :: Hs.Int32,
                         scalar32F32 :: HsProtobuf.Fixed Hs.Word32,
                         scalar32Sf32 :: HsProtobuf.Fixed Hs.Int32}
              deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
 
instance HsProtobuf.Named Scalar32 where
        nameOf _ = (Hs.fromString "Scalar32")
 
instance HsProtobuf.Message Scalar32 where
        encodeMessage _
          Scalar32{scalar32I32 = scalar32I32, scalar32U32 = scalar32U32,
                   scalar32S32 = scalar32S32, scalar32F32 = scalar32F32,
                   scalar32Sf32 = scalar32Sf32}
          = (Hs.mconcat
               [(HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 1)
                   scalar32I32),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 2)
                   scalar32U32),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 3)
                   (HsProtobuf.Signed scalar32S32)),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 4)
                   scalar32F32),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 5)
                   (HsProtobuf.Signed scalar32Sf32))])
        decodeMessage _
          = (Hs.pure Scalar32) <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 1))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 2))
              <*>
              ((Hs.pure HsProtobuf.signed) <*>
                 (HsProtobuf.at HsProtobuf.decodeMessageField
                    (HsProtobuf.FieldNumber 3)))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 4))
              <*>
              ((Hs.pure HsProtobuf.signed) <*>
                 (HsProtobuf.at HsProtobuf.decodeMessageField
                    (HsProtobuf.FieldNumber 5)))
        dotProto _
          = [(HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 1)
                (HsProtobuf.Prim HsProtobuf.Int32)
                (HsProtobuf.Single "i32")
                []
                Hs.Nothing),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 2)
                (HsProtobuf.Prim HsProtobuf.UInt32)
                (HsProtobuf.Single "u32")
                []
                Hs.Nothing),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 3)
                (HsProtobuf.Prim HsProtobuf.SInt32)
                (HsProtobuf.Single "s32")
                []
                Hs.Nothing),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 4)
                (HsProtobuf.Prim HsProtobuf.Fixed32)
                (HsProtobuf.Single "f32")
                []
                Hs.Nothing),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 5)
                (HsProtobuf.Prim HsProtobuf.SFixed32)
                (HsProtobuf.Single "sf32")
                []
                Hs.Nothing)]
 
data Scalar64 = Scalar64{scalar64I64 :: Hs.Int64,
                         scalar64U64 :: Hs.Word64, scalar64S64 :: Hs.Int64,
                         scalar64F64 :: HsProtobuf.Fixed Hs.Word64,
                         scalar64Sf64 :: HsProtobuf.Fixed Hs.Int64}
              deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
 
instance HsProtobuf.Named Scalar64 where
        nameOf _ = (Hs.fromString "Scalar64")
 
instance HsProtobuf.Message Scalar64 where
        encodeMessage _
          Scalar64{scalar64I64 = scalar64I64, scalar64U64 = scalar64U64,
                   scalar64S64 = scalar64S64, scalar64F64 = scalar64F64,
                   scalar64Sf64 = scalar64Sf64}
          = (Hs.mconcat
               [(HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 1)
                   scalar64I64),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 2)
                   scalar64U64),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 3)
                   (HsProtobuf.Signed scalar64S64)),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 4)
                   scalar64F64),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 5)
                   (HsProtobuf.Signed scalar64Sf64))])
        decodeMessage _
          = (Hs.pure Scalar64) <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 1))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 2))
              <*>
              ((Hs.pure HsProtobuf.signed) <*>
                 (HsProtobuf.at HsProtobuf.decodeMessageField
                    (HsProtobuf.FieldNumber 3)))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 4))
              <*>
              ((Hs.pure HsProtobuf.signed) <*>
                 (HsProtobuf.at HsProtobuf.decodeMessageField
                    (HsProtobuf.FieldNumber 5)))
        dotProto _
          = [(HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 1)
                (HsProtobuf.Prim HsProtobuf.Int64)
                (HsProtobuf.Single "i64")
                []
                Hs.Nothing),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 2)
                (HsProtobuf.Prim HsProtobuf.UInt64)
                (HsProtobuf.Single "u64")
                []
                Hs.Nothing),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 3)
                (HsProtobuf.Prim HsProtobuf.SInt64)
                (HsProtobuf.Single "s64")
                []
                Hs.Nothing),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 4)
                (HsProtobuf.Prim HsProtobuf.Fixed64)
                (HsProtobuf.Single "f64")
                []
                Hs.Nothing),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 5)
                (HsProtobuf.Prim HsProtobuf.SFixed64)
                (HsProtobuf.Single "sf64")
                []
                Hs.Nothing)]
 
data ScalarFP = ScalarFP{scalarFPF :: Hs.Float,
                         scalarFPD :: Hs.Double}
              deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
 
instance HsProtobuf.Named ScalarFP where
        nameOf _ = (Hs.fromString "ScalarFP")
 
instance HsProtobuf.Message ScalarFP where
        encodeMessage _
          ScalarFP{scalarFPF = scalarFPF, scalarFPD = scalarFPD}
          = (Hs.mconcat
               [(HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 1)
                   scalarFPF),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 2)
                   scalarFPD)])
        decodeMessage _
          = (Hs.pure ScalarFP) <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 1))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 2))
        dotProto _
          = [(HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 1)
                (HsProtobuf.Prim HsProtobuf.Float)
                (HsProtobuf.Single "f")
                []
                Hs.Nothing),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 2)
                (HsProtobuf.Prim HsProtobuf.Double)
                (HsProtobuf.Single "d")
                []
                Hs.Nothing)]
 
data Stringly = Stringly{stringlyStr :: Hs.Text,
                         stringlyBs :: Hs.ByteString}
              deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
 
instance HsProtobuf.Named Stringly where
        nameOf _ = (Hs.fromString "Stringly")
 
instance HsProtobuf.Message Stringly where
        encodeMessage _
          Stringly{stringlyStr = stringlyStr, stringlyBs = stringlyBs}
          = (Hs.mconcat
               [(HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 1)
                   stringlyStr),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 2)
                   stringlyBs)])
        decodeMessage _
          = (Hs.pure Stringly) <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 1))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 2))
        dotProto _
          = [(HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 1)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "str")
                []
                Hs.Nothing),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 2)
                (HsProtobuf.Prim HsProtobuf.Bytes)
                (HsProtobuf.Single "bs")
                []
                Hs.Nothing)]
 
data Repeat = Repeat{repeatI32s :: Hs.Vector Hs.Int32,
                     repeatI64s :: Hs.Vector Hs.Int64}
            deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
 
instance HsProtobuf.Named Repeat where
        nameOf _ = (Hs.fromString "Repeat")
 
instance HsProtobuf.Message Repeat where
        encodeMessage _
          Repeat{repeatI32s = repeatI32s, repeatI64s = repeatI64s}
          = (Hs.mconcat
               [(HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 1)
                   (HsProtobuf.PackedVec repeatI32s)),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 2)
                   (HsProtobuf.PackedVec repeatI64s))])
        decodeMessage _
          = (Hs.pure Repeat) <*>
              ((Hs.pure HsProtobuf.packedvec) <*>
                 (HsProtobuf.at HsProtobuf.decodeMessageField
                    (HsProtobuf.FieldNumber 1)))
              <*>
              ((Hs.pure HsProtobuf.packedvec) <*>
                 (HsProtobuf.at HsProtobuf.decodeMessageField
                    (HsProtobuf.FieldNumber 2)))
        dotProto _
          = [(HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 1)
                (HsProtobuf.Repeated HsProtobuf.Int32)
                (HsProtobuf.Single "i32s")
                []
                Hs.Nothing),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 2)
                (HsProtobuf.Repeated HsProtobuf.Int64)
                (HsProtobuf.Single "i64s")
                []
                Hs.Nothing)]
 
data Nested = Nested{nestedNestedInner ::
                     Hs.Maybe Proto3.Suite.DotProto.Generate.JSONPBProto.Nested_Inner}
            deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
 
instance HsProtobuf.Named Nested where
        nameOf _ = (Hs.fromString "Nested")
 
instance HsProtobuf.Message Nested where
        encodeMessage _ Nested{nestedNestedInner = nestedNestedInner}
          = (Hs.mconcat
               [(HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 1)
                   (HsProtobuf.Nested nestedNestedInner))])
        decodeMessage _
          = (Hs.pure Nested) <*>
              ((Hs.pure HsProtobuf.nested) <*>
                 (HsProtobuf.at HsProtobuf.decodeMessageField
                    (HsProtobuf.FieldNumber 1)))
        dotProto _
          = [(HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 1)
                (HsProtobuf.Prim (HsProtobuf.Named (HsProtobuf.Single "Inner")))
                (HsProtobuf.Single "nestedInner")
                []
                Hs.Nothing)]
 
data Nested_Inner = Nested_Inner{nested_InnerI64 :: Hs.Int64}
                  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)
 
instance HsProtobuf.Named Nested_Inner where
        nameOf _ = (Hs.fromString "Nested_Inner")
 
instance HsProtobuf.Message Nested_Inner where
        encodeMessage _ Nested_Inner{nested_InnerI64 = nested_InnerI64}
          = (Hs.mconcat
               [(HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 1)
                   nested_InnerI64)])
        decodeMessage _
          = (Hs.pure Nested_Inner) <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 1))
        dotProto _
          = [(HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 1)
                (HsProtobuf.Prim HsProtobuf.Int64)
                (HsProtobuf.Single "i64")
                []
                Hs.Nothing)]